= Day 00000110
:hp-tags: React, 

== Today's coding
I've been pretty unmotivated with React still, but have perservered a little to knock up a simple toy app that replays the text that is typed into a `<textarea>`. It essentially has exactly the same functionality as the first example app made in the tutorial series I'm watching, but I wrote it from scratch and moved the components around a little in the folder structure. I did have to lean on the example pretty heavily, so I can't claim much credit, but it has at least given me a start.

== Tomorrow's coding
The thing I made today is actually part of the way towards completing the first FCC React challenge: link:https://www.freecodecamp.com/challenges/build-a-markdown-previewer[Building a Markdown Previewer]. This means I'm at a little fork in the road. I can either try to implement the Markdown parsing and try to complete the challenge, or I can continue learning more React so that I can better understand what I'm actually doing.

== My problem with React
I think the reason I have struggled with React so far has been it's similarity to Classes in Python. I really struggled to get Classes in Python, so meeting something similar in JavaScript has taken the wind out of my sails a little. In this context, though, they are making a little more sense, so I am hoping that if I perserver just a little more then I might actually end up doing a better job in Python as well as JS. Very oddly, the `this` syntax in JS has kinda helped make the `self` syntax from Python a little clearer. 