= 01100100 Days of Code: Day 00000001
:hp-tags: #100daysOfCode, hubpress, jQuery

I have been working through link:http://freecodecamp.com[Free Code Camp] for a few months now, but have recently decided to commit to the 100 Days of Code challenge.

I've been pretty consistently putting in a couple of hours a night anyway, but keeping a record as I learn more should help me stay on track. All my progress up until this point can be seen at my link:http://jacksonbates.me[portfolio] (modified from an early FCC project, naturally). I've completed the Front End pathway, and the API / Microservice section of the Back End pathway. I feel like mixing things up now, so maybe some React is in order?

== Today's coding

The last couple of days have seen me port my portfolio over to Bootstrap 4 (alpha) and set up all of my previous projects as GitHub pages. Today, I added this Hubpress blog to my GitHub pages set up.

I nearly went with a Jekyll based blog solution, but the theme I loved was going to need me to learn Gulp and get Ruby working on my Windows machine...I thought I'd spend all my time on that, so opted for a pretty nice GUI based gh-pages blog instead. Ta da!

My real coding challenge for the evening, though, was to implement smooth scrolling on my portfolio. Thanks to CSS Tricks, I was able to get a 90% solution rolled out in minutes with the code snippet here: https://css-tricks.com/snippets/jquery/smooth-scrolling/, but I am having some trouble with the smooth scroll returning to the `#top` anchor.

== Tomorrow's coding

- Fix the `#top` smooth scroll issue;
- Start learning React for the FCC Data Viz pathway.